### PR TITLE
digest: Complete implementation of DigestMD5 mech.

### PR DESCRIPTION
**Pull request by ceache**
This pull request combines finishing the DigestMD5 authentication mechanism implementation (until `complete=True`) with a couple of fixes for bytes/str parsing (`parse_challenge` should take in bytes to align with the other mechanisms' `process`/`response` behaviors).

### CODE REVIEW

**Comment by ashafer01** [comment]
Hi @ceache, thanks for the PR, these all look like okay changes to me, but can you add or update the tests to cover your additions? I noticed you removed the `# untested` flag on `authenticate_server()` but it is still not covered.

**Comment by ceache** [comment]
Ok.

Are you opposed to me adding codecov integration?

**Comment by ashafer01** [comment]
It would be much appreciated.

**Comment by bjmb** [comment]
Just reading this, I've added a test for that in https://github.com/thobbs/pure-sasl/pull/27 in case it's useful

**Comment by ashafer01** [comment]
@bjmb Thank you! I will go ahead and merge this and then move over to #27 to get the build passing again with your tests.

**Comment by ceache** [comment]
Thanks @bjmb for taking care of this

**Pull request merged**
